export const GET_LOGIN_REQUEST = 'GET_LOGIN_REQUEST';
export const GET_LOGIN_SUCCESS = 'GET_LOGIN_SUCCESS';
export const GET_LOGIN_FAILURE = 'GET_LOGIN_FAILURE';

export const SET_NEW_PARTNER_REQUEST = 'SET_NEW_PARTNER_REQUEST';
export const SET_NEW_PARTNER_SUCCESS = 'SET_NEW_PARTNER_SUCCESS';
export const SET_NEW_PARTNER_FAILURE = 'SET_NEW_PARTNER_FAILURE';

export const GET_ALL_PARTNERS_REQUEST = 'GET_ALL_PARTNERS_REQUEST';
export const GET_ALL_PARTNERS_SUCCESS = 'GET_ALL_PARTNERS_SUCCESS';
export const GET_ALL_PARTNERS_FAILURE = 'GET_ALL_PARTNERS_FAILURE';

export const DELETE_PARTNER_REQUEST = 'DELETE_PARTNER_REQUEST';
export const DELETE_PARTNER_SUCCESS = 'DELETE_PARTNER_SUCCESS';
export const DELETE_PARTNER_FAILURE = 'DELETE_PARTNER_FAILURE';

export const RESET_STATE = 'RESET_STATE';

export const GET_PARTNER_REQUEST = 'GET_PARTNER_REQUEST';
export const GET_PARTNER_SUCCESS = 'GET_PARTNER_SUCCESS';
export const GET_PARTNER_FAILURE = 'GET_PARTNER_FAILURE';

export const EDIT_PARTNER_REQUEST = 'EDIT_PARTNER_REQUEST';
export const EDIT_PARTNER_SUCCESS = 'EDIT_PARTNER_SUCCESS';
export const EDIT_PARTNER_FAILURE = 'EDIT_PARTNER_FAILURE';

export const GET_MY_DATA_REQUEST = 'GET_MY_DATA_REQUEST';
export const GET_MY_DATA_SUCCESS = 'GET_MY_DATA_SUCCESS';
export const GET_MY_DATA_FAILURE = 'GET_MY_DATA_FAILURE';

export const UPDATE_MY_DATA_REQUEST = 'UPDATE_MY_DATA_REQUEST';
export const UPDATE_MY_DATA_SUCCESS = 'UPDATE_MY_DATA_SUCCESS';
export const UPDATE_MY_DATA_FAILURE = 'UPDATE_MY_DATA_FAILURE';