export const GET_LOGIN_REQUEST = 'GET_LOGIN_REQUEST';
export const GET_LOGIN_SUCCESS = 'GET_LOGIN_SUCCESS';
export const GET_LOGIN_FAILURE = 'GET_LOGIN_FAILURE';

export const SET_NEW_PARTNER_REQUEST = 'SET_NEW_PARTNER_REQUEST';
export const SET_NEW_PARTNER_SUCCESS = 'SET_NEW_PARTNER_SUCCESS';
export const SET_NEW_PARTNER_FAILURE = 'SET_NEW_PARTNER_FAILURE';

export const GET_ALL_PARTNERS_REQUEST = 'GET_ALL_PARTNERS_REQUEST';
export const GET_ALL_PARTNERS_SUCCESS = 'GET_ALL_PARTNERS_SUCCESS';
export const GET_ALL_PARTNERS_FAILURE = 'GET_ALL_PARTNERS_FAILURE';