export const RESET_STATE = 'RESET_STATE';

export const GET_ALL_MY_REQUESTS_REQUEST = 'GET_ALL_MY_REQUESTS_REQUEST';
export const GET_ALL_MY_REQUESTS_SUCCESS = 'GET_ALL_MY_REQUESTS_SUCCESS';
export const GET_ALL_MY_REQUESTS_FAILURE = 'GET_ALL_MY_REQUESTS_FAILURE';

export const SET_NEW_PRODUCT_REQUEST_REQUEST = 'SET_NEW_PRODUCT_REQUEST_REQUEST';
export const SET_NEW_PRODUCT_REQUEST_SUCCESS = 'SET_NEW_PRODUCT_REQUEST_SUCCESS';
export const SET_NEW_PRODUCT_REQUEST_FAILURE = 'SET_NEW_PRODUCT_REQUEST_FAILURE';

export const GET_PRODUCT_REQUEST_REQUEST = 'GET_PRODUCT_REQUEST_REQUEST';
export const GET_PRODUCT_REQUEST_SUCCESS = 'GET_PRODUCT_REQUEST_SUCCESS';
export const GET_PRODUCT_REQUEST_FAILURE = 'GET_PRODUCT_REQUEST_FAILURE';

export const EDIT_PRODUCT_REQUEST_REQUEST = 'EDIT_PRODUCT_REQUEST_REQUEST';
export const EDIT_PRODUCT_REQUEST_SUCCESS = 'EDIT_PRODUCT_REQUEST_SUCCESS';
export const EDIT_PRODUCT_REQUEST_FAILURE = 'EDIT_PRODUCT_REQUEST_FAILURE';

export const GET_ALL_REQUESTS_REQUEST = 'GET_ALL_REQUESTS_REQUEST';
export const GET_ALL_REQUESTS_SUCCESS = 'GET_ALL_REQUESTS_SUCCESS';
export const GET_ALL_REQUESTS_FAILURE = 'GET_ALL_REQUESTS_FAILURE';