export const FETCH_GET_ALL_ORDER_REQUEST = 'FETCH_GET_ALL_ORDER_REQUEST';
export const FETCH_GET_ALL_ORDER_SUCCESS = 'FETCH_GET_ALL_ORDER_SUCCESS';
export const FETCH_GET_ALL_ORDER_FAILURE = 'FETCH_GET_ALL_ORDER_FAILURE';