export const GET_ALL_PRODUCTS_REQUEST = 'GET_ALL_PRODUCTS_REQUEST';
export const GET_ALL_PRODUCTS_SUCCESS = 'GET_ALL_PRODUCTS_SUCCESS';
export const GET_ALL_PRODUCTS_FAILURE = 'GET_ALL_PRODUCTS_FAILURE';

export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE';

export const GET_MY_PRODUCTS_REQUEST = 'GET_MY_PRODUCTS_REQUEST';
export const GET_MY_PRODUCTS_SUCCESS = 'GET_MY_PRODUCTS_SUCCESS';
export const GET_MY_PRODUCTS_FAILURE = 'GET_MY_PRODUCTS_FAILURE';

export const SET_STOCK_REQUEST = 'SET_STOCK_REQUEST';
export const SET_STOCK_SUCCESS = 'SET_STOCK_SUCCESS';
export const SET_STOCK_FAILURE = 'SET_STOCK_FAILURE';

export const RESET_STATE = 'RESET_STATE';